services:
  pathway-server:
    build: .
    container_name: pathway_vectorstore
    command: python -u app/main.py
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - pathway-network

networks:
  pathway-network:
    driver: bridge
