version: '3.9'

services:
  pathway-server:
    build: .
    container_name: pathway_vectorstore
    command: python app/main.py
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    env_file:
      - .env
    restart: unless-stopped


